config:
  target: 'http://localhost:3001'
  phases:
    - duration: 60
      arrivalRate: 100

scenarios:
  - flow:
      - post:
          url: '/vote'
          json:
            chave1: 'participanteA'