version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo

